In [12]:
"""Задание 1**
Напишите функцию, которая классифицирует фильмы из материалов занятия по следующим правилам:
- оценка 2 и меньше - низкий рейтинг
- оценка 4 и меньше - средний рейтинг
- оценка 4.5 и 5 - высокий рейтинг

Результат классификации запишите в столбец class"""

import pandas as pd

movies_id = pd.read_csv('ratings.csv')                                   # читаем из файла ratings.csv
selected_movies_id = movies_id[['movieId', 'rating']]                    # выбираем 2 столбца для представления
movies_name = pd.read_csv('movies.csv')[['movieId', 'title']]            # читаем из файла movies.csv и выбираем нужные столбцы
joined = selected_movies_id.merge(movies_name, on='movieId', how='left') # соединяем данные таблиц по столбцу movieId

def level_ratings(param):                                                # пишем логику классификации фильмов 
    if param['rating'] <= 2:
        return 'Низкий рейтинг'
    elif 2 < param['rating'] <= 4:
        return 'Средний рейтинг'
    else: return 'Высокий рейтинг'

joined['class'] = joined.apply(level_ratings, axis=1)                   # создаем столбец class 
joined.head(10)                                                         # и применяем к нему написанную функцию

,movieId,rating,title,class
0,31,2.5,Dangerous Minds (1995),Средний рейтинг
1,1029,3.0,Dumbo (1941),Средний рейтинг
2,1061,3.0,Sleepers (1996),Средний рейтинг
3,1129,2.0,Escape from New York (1981),Низкий рейтинг
4,1172,4.0,Cinema Paradiso (Nuovo cinema Paradiso) (1989),Средний рейтинг
5,1263,2.0,"Deer Hunter, The (1978)",Низкий рейтинг
6,1287,2.0,Ben-Hur (1959),Низкий рейтинг
7,1293,2.0,Gandhi (1982),Низкий рейтинг
8,1339,3.5,Dracula (Bram Stoker's Dracula) (1992),Средний рейтинг
9,1343,2.0,Cape Fear (1991),Низкий рейтинг

In [55]:
"""Задание 2
Используем файл keywords.csv.

Необходимо написать гео-классификатор, который каждой строке сможет выставить 
географическую принадлежность определенному региону. 
Т. е. если поисковый запрос содержит название города региона, 
то в столбце ‘region’ пишется название этого региона. 
Если поисковый запрос не содержит названия города, то ставим ‘undefined’.

Правила распределения по регионам Центр, Северо-Запад и Дальний Восток
приведены в задании.
Результат классификации запишите в отдельный столбец region"""


"""Ищем "словарные" города в поисковом запросе"""

import pandas as pd

reg_table = pd.read_csv('keywords.csv')

geo_data_frame = {

'Центр': ['москва', 'тула', 'ярославль'],
'Северо-Запад': ['петербург', 'псков', 'мурманск'],
'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск']
}

def geo_classified(param):
    new_string = param.lower().strip()                      # форматируем строку из таблицы поисковика
    for region_name, city_list in geo_data.items():         # идем по циклу геословаря: по ключам и значениям
        for city in city_list:                              # для города в значениях:
            if city in new_string:                          # если город найден в строке поисковика ('москва' in 'кроссовки москва'),
                return region_name                          # возвращаем регион 
    return 'undefined'

reg_table['region'] = reg_table['keyword'].apply(geo_classified)
reg_table.head(20)

                       keyword     shows     region
0                           вк  64292779  undefined
1                одноклассники  63810309  undefined
2                        порно  41747114  undefined
3                         ютуб  39995567  undefined
4                    вконтакте  21014195  undefined
5   одноклассники моя страница  19976138  undefined
6                         майл  15144673  undefined
7                        авито  14786593  undefined
8                   переводчик  14453469  undefined
9                       яндекс  13344734  undefined
10             сбербанк онлайн  10725673  undefined
11                        mail   7687204  undefined
12                        игры   6075762  undefined
13                     youtube   5729958  undefined
14      вконтакте моя страница   5971451  undefined
15                        секс   5431732  undefined
16                        гугл   5175471  undefined
17                          dr   4880955  undefined
18                 алиэкспресс   4879645  undefined
19                     рамблер   4540421  undefined

In [ ]:
"""Второй вариант решения предыдущей задачи.
Проверяем каждое слово из поискового запроса в списке "словарных" городов"""

def geo_classified(param):
    new_string = param.split(' ')                            # форматируем строку из таблицы поисковика (делим на список по пробелу)
    for word in new_string:                                  # для слова из строки поисковика:
        word = word.lower().strip()                          # форматируем его
        for region_name, city_list in geo_data.items():      # цикл по ключам и значениям геословаря:
            if word in city_list:                            # если слово из поисковика находится в словаре, 
                return region_name                           # возвращаем регион 
    return 'undefined'